### ISSUE TITLE
in the transformer part, is there any Pytorch  API to  Transformer Encoder?

### ISSUE THREAD

**Issue by cqlouis** [Wenxuan-1119/TransBTS#12]
Hi Dude , good afternoon.
I'm reading your code. To my understanding , Transformer.py  is for define the transformer encoder.  
I'm wondering whether  there is any API that we can use directly  instead of tedious coding.

I just found  torch.nn.TransformerEncoder  exists.  Is it usable in this project? Have you ever thought about this problem before?

Many thanks!

**Comment by Wenxuan-1119** [comment]
Thanks for your questions, bro. As for API that we can use directly instead of tedious coding, I recommend timm for you. It's very convenient and useful. You can check for it for more details.
