### ISSUE TITLE
output

### ISSUE THREAD

**Issue by wangn123** [Wenxuan-1119/TransBTS#16]
Thanks for your great work.  But when I finished the test, why did the output image like this?
![image](https://user-images.githubusercontent.com/56376393/120773183-ab30ed80-c553-11eb-8c0c-da719811f604.png)

Looking forward to your reply.

**Comment by Wenxuan-1119** [comment]
There must be some errors in your code of visualization.Here is an example of our visualization results.
![image](https://user-images.githubusercontent.com/56334198/122166812-ac93db80-ceac-11eb-909b-be2b1c8356e9.png)
