### ISSUE TITLE
On the Number of GPUs

### ISSUE THREAD

**Issue by Li-bingjie48** [Wenxuan-1119/TransBTS#17]
Hello, I see that you use four GPUs to run the code. Is there only one GPU in my computer that can run through? Look forward to your reply.

**Comment by gshaowei1996** [comment]
可以，但是如果使用一块GPU来训练的话，当batchsize设置为2的时候，显存已经需要24g了，所以你如果仅有一块GPU的话，估计得是3090，代码只用将分布式改为非分布式训练即可

**Comment by Li-bingjie48** [comment]
谢谢你的解答 非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wenxuan-1119/TransBTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 晚上9:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Wenxuan-1119/TransBTS] On the Number of GPUs (#17)





 
可以，但是如果使用一块GPU来训练的话，当batchsize设置为2的时候，显存已经需要24g了，所以你如果仅有一块GPU的话，估计得是3090，代码只用将分布式改为非分布式训练即可

**Comment by Lnan1615** [comment]
我也只有一块3090，但是我不太清楚要怎么改非分布式，有改好的的代码让我学习一下吗？

**Comment by jiangllll** [comment]
> 



> Hello, I see that you use four GPUs to run the code. Is there only one GPU in my computer that can run through? Look forward to your reply.

@Li-bingjie48 你好，你实现单卡运行的代码了嘛，想参考一下

**Comment by Lnan1615** [comment]
我改了代码，也跑通了，但是结果的波动超级大，不收敛的样子，你改出来的代码也是这个样子吗？

**Comment by jiangllll** [comment]
> 我改了代码，也跑通了，但是结果的波动超级大，不收敛的样子，应该是我哪里改的有问题。你改出来的代码也是这个样子吗？

能让我参考下嘛，不太会改代码，感谢，qq邮箱 3057748270@qq.com

**Comment by chjwhere** [comment]
> 我改了代码，也跑通了，但是结果的波动超级大，不收敛的样子，应该是我哪里改的有问题。你改出来的代码也是这个样子吗？

你好，请问你们是如何将分布式训练更改为非分布式训练？我也仅有一张3090，但是不太懂得如何更改代码以训练。希望能得到你们的回复，万分感谢！1641377171@qq.com

**Comment by chjwhere** [comment]
> > 我改了代码，也跑通了，但是结果的波动超级大，不收敛的样子，应该是我哪里改的有问题。你改出来的代码也是这个样子吗？
> 
> 能让我参考下嘛，不太会改代码，感谢，qq邮箱 [3057748270@qq.com](mailto:3057748270@qq.com)

你好，请问你们是如何将分布式训练更改为非分布式训练？我也仅有一张3090，但是不太懂得如何更改代码以训练。希望能得到你们的回复，万分感谢！1641377171@qq.com

**Comment by Taocunguo** [comment]
> 我改了代码，也跑通了，但是结果的波动超级大，不收敛的样子，应该是我哪里改的有问题。你改出来的代码也是这个样子吗？

你好，我也不太会改代码，请问你可以也发一份改好的给我吗，万分谢谢。1460535844@qq.com

**Comment by listener114** [comment]
> 我改了代码，也跑通了，但是结果的波动超级大，不收敛的样子，应该是我哪里改的有问题。你改出来的代码也是这个样子吗？

你好，能参考下如何修改代码的吗，万分感谢 3236243148@qq.com
