### ISSUE TITLE
Can u plz give some idea about resuming training if interrupted in between

### ISSUE THREAD

**Issue by gjkaur** [Wenxuan-1119/TransBTS#21]
Hello wenxuan. I hope you recognize me. I had raised an issue earlier about predictions on brats 2020 data.
I  need your help in resuming the training. I am training model on google colab which shuts after 12 hours. So I want to resume it from the same point where it gets stopped.

**Comment by Wenxuan-1119** [comment]
Hi,gjkaur,I remebered you,bro. Our training code already achieves the goal of resuming the training. To save the model weight of the intermediate process, all you have to do is adjusting this parameter ('--save_freq', default=1000, type=int).
