### ISSUE TITLE
数据集怎么处理

### ISSUE THREAD

**Issue by dengshuang-RGB** [Wenxuan-1119/TransBTS#29]
您好，最近在复现您的代码呢，但是我第一步就遇到了问题，看您的data里有train.txt，这是处理过后的吗？能讲解一下数据处理导入这一块是怎么回事吗？谢谢您

**Comment by XJWang0** [comment]
> 您好，最近在复现您的代码呢，但是我第一步就遇到了问题，看您的data里有train.txt，这是处理过后的吗？能讲解一下数据处理导入这一块是怎么回事吗？谢谢您

请问你数据处理的部分解决了吗？
