### ISSUE TITLE
Subject Split file missing

### ISSUE THREAD

**Issue by vincentme** [Wenxuan-1119/TransBTS#3]
Hi Wenxuan

I am currently running your code. After downloading the MICCAI_BraTS_2019_Data, I found that there is no subject split files ' flist' like 'all.txt' or 'valid.txt'. So could not run the preprocess? Will you provide these files? Thanks

**Comment by Wenxuan-1119** [comment]
Thanks for your advice, and I have already upload the txt files for training and validation. Hope it would help you.
