### ISSUE TITLE
About 3D transformer

### ISSUE THREAD

**Issue by vv123-star** [Wenxuan-1119/TransBTS#7]
Hello, I  run the tranBTS code for 3D medical images, the shape of the generated attention weight is (Batch_size,num_heads, n_patches,n_patches ), is this not applicable to 3D images? 
Thank you in advance!

**Comment by Wenxuan-1119** [comment]
Thanks for your questions. In fact, I am sure what is your question. After downsampling, we reshape each volume into a feature vector instead of patch. I think you might be wondering is the way of patch-style applicable to 3D images.  You can check for more details from our paper.
