### ISSUE TITLE
why are there  no label 0 in my predict ? 

### ISSUE THREAD

**Issue by cqlouis** [Wenxuan-1119/TransBTS#9]
My dear friend,  when I run your code,  there are only label 1,2,4 in my result .   All the background are label 1,  I was puzzled.
I just only download your code here , then change the path to my environment, and  edit the parallel code into  single GPU.  
My platform is Ubuntu20.04 + RXT 3090.

Have you ever encountered the same problem ?

Would you please give me some  suggestions? 

Many thanks in advance!

**Comment by cqlouis** [comment]
It seems all the background are label 1, and edema  is label 2,  ET is label 4, NET is label 1.

**Comment by Wenxuan-1119** [comment]
可以把你QQ给我，我们交流一下，我之前没遇到这种问题，因为np.zeros()已经初始0为背景了。

**Comment by Wenxuan-1119** [comment]
如果问题已经解决了的话，我就close了哈。

**Comment by wangyunyuwyy** [comment]
> > My dear friend, when I run your code, there are only label 1,2,4 in my result . All the background are label 1, I was puzzled. I just only download your code here , then change the path to my environment, and edit the parallel code into single GPU. My platform is Ubuntu20.04 + RXT 3090.
> > Have you ever encountered the same problem ?
> > Would you please give me some suggestions?
> > Many thanks in advance!
> > hi
> > did u fix the problem ?  how? please  give me some advice

请问您这个问题得到解决了吗？我也遇到了这样的问题，期待您的回复。
